### ISSUE TITLE
[REQUEST] Support multi points.

### ISSUE THREAD

**Issue by finscn** [gre/bezier-easing-editor#11]
Like this : 

![image](https://user-images.githubusercontent.com/288367/54884086-cf8add00-4ea7-11e9-82f8-fe723653625e.png)

In fact , it creates multi bezier curves , 
the endpoint of  the-Nth,  is the startpoint of  the (N+1)th.

Thanks .

**Comment by gre** [comment]
See library called `ipo`

**Comment by gre** [comment]
https://github.com/gre/ipo

**Comment by finscn** [comment]
Thanks
