### ISSUE TITLE
great demo

### ISSUE THREAD

**Issue by darul75** [gre/bezier-easing-editor#4]
hit @gre 

I really like you editor demo and would like to know more about how you handle your progression line velocity with React

How do you process to make it drawing automaticaly more or less drawing fast ?

![capture](https://cloud.githubusercontent.com/assets/2134003/13292705/218d2c18-db1d-11e5-93d8-3f99354742a1.PNG)

**Comment by gre** [comment]
it is done with `bezier-easing` library.
